//
// Created by pietr on 01/04/2024.
//

#ifndef COLOR_CONVERSION_SRGB_TO_SPECTRUM_H
#define COLOR_CONVERSION_SRGB_TO_SPECTRUM_H

/*
 * Tables used to convert an sRGB color into an approximated reflectance/illuminance spectrum
 * These tables were generated by writing a script that implements the "main()" function
 * of this file in the pbrt-v4 repo:
 * https://github.com/mmp/pbrt-v4/blob/39e01e61f8de07b99859df04b271a02a53d9aeb2/src/pbrt/cmd/rgb2spec_opt.cpp#L4
 *
 * More sources: https://www.pbr-book.org/4ed/Radiometry,_Spectra,_and_Color/Color
 */

extern const int sRGBToSpectrumTable_Res;
extern const float sRGBToSpectrumTable_Scale[64];
extern const float sRGBToSpectrumTable_Data[3][64][64][64][3];

__constant__ inline int dev_sRGBToSpectrumTable_Res;
__constant__ inline float dev_sRGBToSpectrumTable_Scale[64];

#endif //COLOR_CONVERSION_SRGB_TO_SPECTRUM_H
